# Generated by Django 4.2.6 on 2023-10-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(help_text='CPF - Apenas Números', max_length=11)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
    ]
